# Configuration for Alacritty
#
# by Tadeas Uhlir <tadeas.uhlir@gmail.com>

[general]
# Import theme
import = ["~/.config/alacritty/theme.toml"]

# Font configuration
[font]
size = 12.0

[font.normal]
family = "BlexMono Nerd Font"
style = "Regular"

[font.italic]
family = "BlexMono Nerd Font"
style = "Italic"

[font.bold]
family = "BlexMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "BlexMono Nerd Font"
style = "Bold Italic"

[window]
# Make option act as alt. macOS only option.
option_as_alt = "Both"
