[colors.primary]
background = "#f3ead3"
foreground = "#5c6a72"

[colors.normal]
black = "#f3ead3"
red = "#f9706d"
# green = "#a5bc01"
green = "#a2b901"
yellow = "#febb10"
blue = "#5ba6ce"
magenta = "#e689c9"
cyan = "#41c292"
white = "#829181"

[colors.bright]
# black = "#d8d3ba"
black = "#b9c0ab"
red = "#f85552"
green = "#8da101"
yellow = "#dfa000"
blue = "#3a94c5"
magenta = "#df69ba"
cyan = "#35a77c"
white = "#5c6a72"

# Nice lighter color used for taskwarrior alternate bg and blocking fg
[[colors.indexed_colors]]
color = "#f6f0df"
index = 229

# Everforest orange color
[[colors.indexed_colors]]
color = "#e69875"
index = 215

[env]
THEMENAME = "everforest"
THEMEBG = "light"
BAT_THEME = "gruvbox-light"
