#!/usr/bin/env bash

vim_windows=$(tmux list-panes -a -F '#{pane_current_command} #S:#I.#P' | grep -i vim | cut -d ' ' -f2)

for v_win in $vim_windows; do
    tmux wait-for -L "lock-${v_win}"
    # tmux set-hook -t "$v_win" alert-activity "kill-session -C; set-hook -ut $v_win alert-activity"
    # tmux send-keys -t "$v_win" "Escape" ":silent !tmux set monitor-activity off"
    tmux send-keys -t "$v_win" "Escape" ":call SetGruvBackground('${THEMEBG:-dark}')" "Enter"
    tmux send-keys -t "$v_win" ":silent exec '!tmux wait-for -U lock-${v_win}' | echo" "Enter"
done

for v_win in $vim_windows; do
    tmux wait-for -L "lock-${v_win}"
    tmux wait-for -U "lock-${v_win}"
done

for v_sess in $(echo "$vim_windows" | cut -d ':' -f1 | uniq); do
    sleep 0.05 && tmux kill-session -C -t "$v_sess"
done
